export enum Entity {
  dashboard = "dashboard",
  myschedule = "myschedule",
  warehouse = "warehouse",
  projects = "projects",
  crewPlanner = "crewPlanner",
  subhire = "subhire",
  subhireShortage = "subhireShortage",
  invoices = "invoices",
  equipment = "equipment",
  contacts = "contacts",
  crewMembers = "crewMembers",
  vehicles = "vehicles",
  tasks = "tasks",
  timeRegistration = "timeRegistration",
  maintenance = "maintenance",
  statistics = "statistics",
  configuration = "configuration",
  notifications = "notifications",
  inspections = "inspections",
  repairs = "repairs"
}
