export enum TableEntity {
  dashboard = "dashboardEntity",
  warehouse = "warehouseEntity",
  projects = "projectEntity",
  crewPlanner = "crewPlannerEntity",
  subhire = "subhireEntity",
  subhireShortage = "subhireShortageEntity",
  invoices = "invoiceEntity",
  equipment = "equipmentEntity",
  contacts = "contactEntity",
  crewMembers = "crewMemberEntity",
  vehicles = "vehicleEntity",
  tasks = "taskEntity",
  timeRegistration = "timeRegistrationEntity",
  maintenance = "maintenanceEntity",
  statistics = "statisticEntity",
  configuration = "configurationEntity",
  notifications = "notificationEntity",
  inspections = "inspectionEntity",
  repairs = "repairEntity"
}
